version: '3'

# definiciones de los servicios
services:
  redis:
    image: "redis:alpine"
    ports:
    - "6379:6379"
  worker:
    build: '.'
    depends_on:
      - redis
      #volumes:
       # - ./Worker:/code
    command: python worker.py
    environment:
      PYTHONUNBUFFERED: 1
      REDIS_HOST: redis

  worker2:
    build: '.'
    depends_on:
      - redis
      #volumes:
      # - ./Worker:/code
    command: python worker.py
    environment:
      PYTHONUNBUFFERED: 1
      REDIS_HOST: redis

  worker3:
    build: '.'
    depends_on:
      - redis
      #volumes:
      # - ./Worker:/code
    command: python worker.py
    environment:
      PYTHONUNBUFFERED: 1
      REDIS_HOST: redis

  worker4:
    build: '.'
    depends_on:
      - redis
      #volumes:
      # - ./Worker:/code
    command: python worker.py
    environment:
      PYTHONUNBUFFERED: 1
      REDIS_HOST: redis

  worker5:
    build: '.'
    depends_on:
      - redis
      #volumes:
      # - ./Worker:/code
    command: python worker.py
    environment:
      PYTHONUNBUFFERED: 1
      REDIS_HOST: redis
  worker6:
    build: '.'
    depends_on:
      - redis
      #volumes:
      # - ./Worker:/code
    command: python worker.py
    environment:
      PYTHONUNBUFFERED: 1
      REDIS_HOST: redis

  worker7:
    build: '.'
    depends_on:
      - redis
      #volumes:
      # - ./Worker:/code
    command: python worker.py
    environment:
      PYTHONUNBUFFERED: 1
      REDIS_HOST: redis